bab:
  dasar:
    nomor: 1
    judul: Pengantar
  env_conf:
    nomor: 2
    judul: Environment dan Konfigurasi
  singkat:
    nomor: 3
    judul: Pemakainan Singkat
  rute:
    nomor: 4
    judul: Rute
  ptr_ref:  
    nomor: 5
    judul: Pointer & Referensi
  file:  
    nomor: 6
    judul: Operasi File
  struct:  
    nomor: 7
    judul: Struct
  union:  
    nomor: 8
    judul: Union
  typedef:  
    nomor: 9
    judul: Typedef
  prepro:  
    nomor: 10
    judul: Preprosesor
  memori:  
    nomor: 11
    judul: Manajemen Memori
  penutup:  
    nomor: 12
    judul: Penutup
