-
  title: "Kontribusi"
  desc:  "Intruksi Penulisan Tutorial dan Penggunaannya"
  nama:  kontribusi
  url:   "bebas/kontribusi"
  rilis: true
-
  title: "SQLite"
  desc:  "Kuliah SQLite3 oleh Syandal_ di #ubuntu-indenesia @ freenode"
  nama:  sqlite
  url:   "bebas/sqlite"
  rilis: true
