-
  title: "Kontribusi"
  desc:  "Intruksi Penulisan Tutorial dan Penggunaannya"
  nama:  kontribusi
  url:   "bebas/kontribusi"
  rilis: true
-
  title: "SQLite"
  desc:  "Tutorial SQLite Dasar oleh Syandal_ di freenode/ubuntu-indenesia"
  nama:  sqlite
  url:   "bebas/sqlite"
  rilis: true
